server:
  port: 8083


yalooStore:
  front: localhost:8082
  shop: localhost:8081
  gateway: localhost:80


application:
  name: yalooStore-auth

jwt:
  secretKey:

spring:
  data:
    redis:
      password:
      database: 0
      host: http://localhost
      port: 6379
  config:
    import: "optional:configserver:"
